//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace displayProduct.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public Nullable<long> OfferId { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public float UnitPrice { get; set; }
        public int TotalStock { get; set; }
        public bool IsDeleted { get; set; }
    }
}
